<template>
  <scroll class="content">
    <ul>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
      <li>商品信息</li>
    </ul>
  </scroll>
</template>

<script>
import Scroll from 'components/common/scroll/Scroll.vue'
export default {
  components:{
    Scroll
  },
  data(){
    return {
    }
  },
  created(){},
  mounted(){},
  watch:{},
  computed:{},
  methods:{},
}
</script>
<style scoped>
  .content{
    height: 300px;
    background-color: red;
    overflow: hidden;
  }
</style>